apiVersion: apps/v1
kind: Deployment
metadata:
  name: contacts-app
spec:
  selector:
    matchLabels:
      app: contacts-app
  template:
    metadata:
      labels:
        app: contacts-app
    spec:
      containers:
        - name: contacts-app
          image: mohim007/chi_pgx_test:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: contacts-config
